---
services:
  cgnatlogger:
    container_name: cgnatlogger
    restart: always
    image: grandow/cgnatlogger:beta4
    volumes:
      - "/srv/cgnatlogger/mysql:/var/lib/mysql"
      - "/srv/cgnatlogger/logs:/var/log/mikrotik"
    environment:
      - TZ=America/Sao_Paulo
      - MIKROTIK_IPS=10.1.1.9
    ports:
      - 14402:80
      - 514:514/udp