---
services:
  cgnatlogger:
    image: grandow/cgnatlogger:beta4
    container_name: cgnatlogger
    restart: always
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./logs:/var/log/mikrotik"
    environment:
      - TZ=America/Sao_Paulo
      # Endereço IP do(s) BRAS 
      - MIKROTIK_IPS=10.0.0.1
      #- MIKROTIK_IPS=10.0.0.1,10.0.0.2,10.0.0.3
    ports:
      - 80:80
      - 514:514/udp