[supervisord]
nodaemon=true

[program:mariadb]
command=/usr/bin/mysqld --datadir=/var/lib/mysql --user=mysql
stdout_logfile=/var/log/mysql/mariadb.log
stderr_logfile=/var/log/mysql/mariadb.err.log
autorestart=true

[program:init]
command=/usr/local/bin/init
user=root
autostart=true
autorestart=false
startretries=3
startsecs=0
stdout_logfile=/var/log/mysql/init.log
stderr_logfile=/var/log/mysql/init.err.log

[program:php-fpm]
command=/usr/sbin/php-fpm82 -F
stdout_logfile=/var/log/nginx/php-fpm.log
stderr_logfile=/var/log/nginx/php-fpm.err.log
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log
autorestart=true

[program:syslog-ng]
command=syslog-ng -F
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/syslog-ng.log
stderr_logfile=/var/log/syslog-ng.err