source s_net {
    udp(port(514));
    tcp(port(514));
};

filter f_mikrotik {
    host(env("MIKROTIK_IP"));
};

# Destino dos logs (arquivo com template dinâmico)
destination df_mikrotik {
    file(
        "/var/log/mikrotik/${HOST}.${YEAR}.${MONTH}.${DAY}.${HOUR}.log"
        template-escape(no)
        create-dirs(yes)
    );
};

# Regra de log
log {
    source(s_net);
    filter(f_mikrotik);
    destination(df_mikrotik);
};